### ISSUE TITLE
Support Android Gradle Plugin 3.6.3 (Lint Level 6)

### ISSUE THREAD

**Issue by TWiStErRob** [littlerobots/rxlint#1]
![image](https://user-images.githubusercontent.com/2906988/85133108-f9a98700-b231-11ea-96b2-2cb6a7615d48.png)

Probably as simple as updating these two?
https://github.com/littlerobots/rxlint/blob/c78d0b054faf47f02d053c2f090f65ea11d69efc/build.gradle#L12
https://github.com/littlerobots/rxlint/blob/c78d0b054faf47f02d053c2f090f65ea11d69efc/build.gradle#L20

**Comment by hvisser** [comment]
This is tied to the lint API, correct and usually bumping that is enough. If you want to give it a go and PR it that would be appreciated, otherwise I'll take a look later!

**Comment by TWiStErRob** [comment]
Don't have much time, thanks for the quick response.
Note: please don't skip this in favor of #2, please release both separately as there could be projects who can't move yet to 4.0.

**Comment by hvisser** [comment]
Quick testing looks like bumping the lint dependencies to the latest version should still work with 3.6.3, so bumping to latest shouldn't be an issue. I've pushed `1.7.6-SNAPSHOT` to `https://oss.sonatype.org/content/repositories/snapshots/` if you want to confirm this.

**Comment by TWiStErRob** [comment]
Please publish a version of RxLint for 3.6.3, because we cannot update to 4.0.0 yet and having a newer version also gives the same Lint warning:
![image](https://user-images.githubusercontent.com/2906988/85282544-d4ac5280-b483-11ea-96fd-d4f68f97ab3d.png)

**Comment by hvisser** [comment]
I'm going to close this and not do anything for 3.5.x. The warning is just a warning and since there's no broken functionality I'd recommend to stay on 1.7.5 with the warning until you're able to upgrade to AGP 4.x and 1.7.6 which I will release in a bit.
