### ISSUE TITLE
Support Android Gradle Plugin 4.0.0 (Lint Level 7)

### ISSUE THREAD

**Issue by TWiStErRob** [littlerobots/rxlint#2]

**Comment by a-kari** [comment]
Hello! I am trying to use RxLint `1.7.6`, but have the following output:

```bash
Could not find nl.littlerobots.rxlint:detector:1.7.6.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/nl/littlerobots/rxlint/detector/1.7.6/detector-1.7.6.pom
  - https://jcenter.bintray.com/nl/littlerobots/rxlint/detector/1.7.6/detector-1.7.6.pom
  - https://repo.maven.apache.org/maven2/nl/littlerobots/rxlint/detector/1.7.6/detector-1.7.6.pom
Required by:
    project :app
```

I have tried to connect RxLint to my project via:

**`./build.gradle`:**

```gradle
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}
```

**`./app/build.gradle`:**

```gradle
dependencies {
    lintChecks "nl.littlerobots.rxlint:detector:1.7.6"
}
```

Perhaps RxLint `1.7.6` is missing on these remote repositories, although `1.7.5` version is fine. Can you please check it?

**Comment by hvisser** [comment]
1.7..6 hasn't been released yet, I will release it today. As a side note, some reported that `lintChecks` might not be working correctly, are you seeing the lint check working with 1.7.5? Otherwise I'll have to update the docs too.

**Comment by hvisser** [comment]
1.7..6 has been released and should show up on Maven Central shorty.

**Comment by a-kari** [comment]
Thank you, `1.7.6` version has become available.

I'm new to RxLint, so I tried to connect it via `lintChecks`, but has just noticed that `lintChecks` does not work (neither with `1.7.5` nor with `1.7.6`).

So I have changed it to `implementation` and run lint checks via `./gradlew lint` command, now warnings are printed.
