### ISSUE TITLE
Use RxJavaPlugins.setErrorHandler(Timber::e) should handle RxSubscribeOnError

### ISSUE THREAD

**Issue by MohamedHashim** [littlerobots/rxlint#5]
By using RxJavaPlugins.setErrorHandler(Timber::e), rxlint should resolve the RxSubscribeOnError because RxJavaPlugins.setErrorHandler is a default handling for RxSubscribeOnError but it keeps showing that error!

**Comment by hvisser** [comment]
Sorry can you clarify what the issue is? If you have a small sample project that reproduces this issue that would be helpful too.

**Comment by MohamedHashim** [comment]
According to this [article](https://medium.com/@s.vinouze/default-error-handling-with-rxjava-89b79de3f125) we should add RxJavaPlugins.setErrorHandler in onCreate of the custom application class and It will receive all exceptions wherever onError implementations are missing. You can state what to perform when such cases occur.
by this way, I have a default handle for all OnErrorNotImplemented exceptions.

for example 

` val subscription = RxPermissions(this).request(Manifest.permission.ACCESS_FINE_LOCATION)
            .subscribe(
                { granted ->
                    BluetoothLocationService.enqueueWork(this, granted)
                }
            )`
this block is highlighted red and shows an error message "**Subscriber is missing onError**" and that's not expected because subscriber has a default error handling.

so, I expect rxlint should check if there is a default handle for OnErrorNotImplemented exceptions, it shouldn't consider this block as a red warning block.

**Comment by hvisser** [comment]
I don't think using using `RxPlugins.setErrorHandler()` means that you don't need any error handling anymore, it is primarily used to catch errors that you forget to catch or errors that happen that never reach your `onError` handlers. In fact, one of the main reasons to create rxlint is to make sure all errors are handled properly. 

So detecting a global error handler is not something that `rxlint` will support. You can disable the specific check in your `lint.xml` by disabling the `RxSubscribeOnError` check if you don't want that check to trigger or suppres the warning in the places where you are sure you don't need an `onError` handler.
